version: '3'

services:
  bot:
    build: .
    command: python telegram.py
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

